### ISSUE TITLE
the requested PHP extension tidy is missing from your system.

### ISSUE THREAD

**Issue by Mywifi** [Stolz/Wiki#2]
$ composer install

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for stolz/laravel-html-tidy dev-master -> satisfiable by stolz/laravel-html-tidy[dev-master].
    - stolz/laravel-html-tidy dev-master requires ext-tidy \* -> the requested PHP extension tidy is missing from your system.

**Comment by Stolz** [comment]
You need to install/enable the [Tidy extension](http://php.net/manual/en/book.tidy.php) of PHP.

If you compiled PHP by yourself try recompiling with the option `--with-tidy`. If you used a precompiled package, search with your package manager for a package named _php-tidy_, _php5-tidy_, _libtidy_, _libtidy-devel_ or similar.

**Comment by Mywifi** [comment]
![image](https://cloud.githubusercontent.com/assets/9286290/11830811/66435eca-a3e3-11e5-9429-0c36a4a61cd0.png)

WampServer 2.5 
tidy extension enabled
still not work

**Comment by Stolz** [comment]
Remeber **composer** uses the cli PHP interpreter. You seem to have enabled the extension only for the Apache module. Enable the extension also in the cli or pass the option `--ignore-platform-reqs` to **composer**.
