### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by q2apro** [Stolz/Wiki#3]
Laravel is unknown to me and I hoped I could install your "Stolz Wiki" on localhost, running PHP. 

However, I cannot figure out the right steps. 

Navigating to the `public` folder throws: 

```
Warning: require(C:\wamp\w\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\w\bootstrap\autoload.php on line 17
```

I am stuck.

PS: Is there any demo online?

**Comment by Stolz** [comment]
There is no online demo. If you are not familiar with Laravel there is no real advantage of using this package vs any other Wiki software. The main point of this package is that it gives you the barebones of the wiki for you to extend or adapt to your own Laravel application.

For installing the package you first need to [install composer](https://getcomposer.org/doc/00-intro.md#installation-windows) and the run 

```
composer create-project stolz/wiki --prefer-dist --stability=dev --no-scripts
```

Then just follow [Laravel instructions](https://laravel.com/docs/5.1/installation#configuration)
