### ISSUE TITLE
Internal Login

### ISSUE THREAD

**Issue by amenk** [Stolz/Wiki#5]
Is it possible to enable the Laravel default login in addition to the 3rd party services.

Especially for testing (but also later in live) this would be nice.

**Comment by Stolz** [comment]
Yes, it is possible. The `User` model implements `Illuminate\Contracts\Auth\Authenticatable` so as long as you login system returns an instance of that contract you can use whatever authentication you want.

The easiest way to use Laravel's built in login system is restoring the [current login controller ](https://github.com/Stolz/Wiki/blob/master/app/Http/Controllers/AuthController.php) with the [default from Laravel](https://github.com/laravel/laravel/blob/5.1/app/Http/Controllers/Auth/AuthController.php). You could even rename the current controller and restore the default one (adjusting routes) and keep both systems at the same time.

BTW, for testing, there is a simple way to authenticate a given user as the current user. Use the method [`$this->actingAs($user)`](https://laravel.com/docs/5.1/testing#sessions-and-authentication)
